# Job Postings: Sample, Methods and Limitations

The reference document behind [What Firms Ask For](./_job_postings_findings_ipynb.ipynb).
Everything the findings page asserts is derived here, and everything it defers
is spelled out here: the sample frame, what each way of counting over- and
under-states, the rules that decide what counts as a mention, and the claims
this data cannot support.

Both notebooks load the same committed tables through `jobpostings.report` and
neither recomputes anything, so the two cannot drift apart on a number.

Nothing here touches the network. Collection is a separate manual step
(`src/collect_parallel.py`); this notebook consumes what that step committed,
which is what makes the figures reproducible from a clone.

In [1]:
from jobpostings import report

d = report.load()
report.headline(d)

collection runs: 2026-09-25, 2026-09-27
11,346 postings from 64 firms
9,237 technical postings
1,600 mention a pipeline, ETL/ELT or orchestration

## What the sample is, and what it is not

The sample frame is `data_manual/manifest.yml`: firms whose careers systems
expose a machine-readable endpoint we have found and validated. That is a real
selection rule with real consequences.

- It is **not a random sample** of quantitative finance. It over-represents
  firms that publish openly and under-represents firms that recruit through
  networks and headhunters. Coverage is systematically worse for banks, which
  run fragmented legacy applicant-tracking systems.
- Postings measure **hiring intent**, not deployed infrastructure. A firm can
  run Airflow for a decade and never name it; a firm can name a tool it is only
  beginning to adopt.
- Firms differ in how specific they are. Some publish their whole stack; others
  name almost nothing. **A zero is ambiguous** between "does not use it" and
  "does not say".

Those are not boilerplate. They are the difference between a defensible reading
and an overreach, and the frame below is printed in full so they can be checked.

## The sample frame

One row per firm. Firms with zero postings are kept rather than dropped: they
are either targets whose route is unresolved, firms whose own system was failing
when we last collected, or firms with no machine-readable board at all. Keeping
them visible preserves the denominator of *attempted* coverage.

In [2]:
frame = d["frame"]
collected = frame[frame["n_postings"] > 0]
pending = frame[frame["n_postings"] == 0]

view = collected[
    ["firm_name", "firm_type", "route", "sampling", "stored_scope",
     "n_postings", "n_technical", "n_pipeline"]
].sort_values("n_postings", ascending=False)
view.columns = [
    "Firm", "Type", "Route", "Sampling", "Stored scope",
    "Postings", "Technical", "Pipeline-mentioning",
]
view.reset_index(drop=True)

                                            Firm           Type              Route Sampling    Stored scope  Postings  Technical  Pipeline-mentioning
0                                  JPMorganChase           bank  oracle_recruiting   census  technical_only      2425       2425                  501
1                                           HSBC           bank          eightfold   census    all_postings      1472        176                   38
2                                           Citi           bank            workday   census  technical_only      1023       1023                  178
3                                  Goldman Sachs           bank  oracle_recruiting   census  technical_only       559        559                   63
4                                       Barclays           bank            workday   census  technical_only       421        421                   80
5                                 Morgan Stanley           bank            workday   census  technical_only       400        400                   50
6                                  Deutsche Bank           bank            workday   census  technical_only       361        361                   46
7                                    Jane Street   prop_trading         greenhouse   census    all_postings       230        150                    4
8                                Bank of America           bank            workday   census  technical_only       220        220                   48
9   Point72 (incl. Cubist Systematic Strategies)     multistrat         greenhouse   census    all_postings       220        166                   23
10                         Millennium Management     multistrat          eightfold   census    all_postings       215        162                   28
11                                      Vanguard  asset_manager            workday   census  technical_only       211        211                   41
12                  Qube Research & Technologies     systematic         greenhouse   census    all_postings       199        182                   31
13                          Fidelity Investments  asset_manager            workday   census  technical_only       192        192                   36
14                            Citadel Securities   market_maker    wayback_sitemap   census    all_postings       189        152                   11
15                                Northern Trust  asset_manager            workday   census  technical_only       181        181                   26
16                                   IMC Trading   market_maker         greenhouse   census    all_postings       175        115                   17
17                                   Wells Fargo           bank            workday   census  technical_only       171        171                   43
18                                       Optiver   market_maker         greenhouse   census    all_postings       166        108                   19
19                                           DRW   prop_trading           drw_next   census    all_postings       164        122                   26
20                                       Citadel     multistrat    wayback_sitemap   census    all_postings       154        108                    2
21                                     BlackRock  asset_manager            workday   census  technical_only       154        154                   49
22                                  Jump Trading   prop_trading         greenhouse   census    all_postings       113         94                   17
23                                    WorldQuant     systematic         greenhouse   census    all_postings       101         87                   18
24                                     Jefferies           bank  oracle_recruiting   census  technical_only        92         92                   16
25                        Tower Research Capital   prop_trading         greenhouse   census    all_postings        91         74                   21
26                          The D. E. Shaw Group     systematic             deshaw   census    all_postings        90         42                    5
27                                       Invesco  asset_manager            workday   census  technical_only        90         90                   18
28                           Squarepoint Capital     systematic         greenhouse   census    all_postings        89         58                   11
29                          Hudson River Trading   prop_trading         greenhouse   census    all_postings        87         62                    5
30                                         PIMCO  asset_manager            workday   census  technical_only        84         84                    3
31                  Schonfeld Strategic Advisors     multistrat         greenhouse   census    all_postings        80         40                    9
32                         Wellington Management  asset_manager            workday   census  technical_only        76         76                    4
33                                 Capital Group  asset_manager            workday   census  technical_only        67         67                   14
34                                 T. Rowe Price  asset_manager            workday   census  technical_only        63         63                   17
35                         Man Group (incl. AHL)  asset_manager         greenhouse   census    all_postings        59         38                    9
36                                     Two Sigma     systematic            avature   census    all_postings        53         43                    9
37                              The Voleon Group     systematic              ashby   census    all_postings        53         38                   15
38                                    G-Research     systematic            workday   census  technical_only        53         53                    6
39                        AQR Capital Management     systematic         greenhouse   census    all_postings        51         36                    4
40                               Virtu Financial   market_maker         greenhouse   census    all_postings        49         36                    1
41                                  Flow Traders   market_maker         greenhouse   census    all_postings        47         33                    2
42                                 Akuna Capital   market_maker         greenhouse   census    all_postings        42         33                    6
43                           Old Mission Capital   market_maker         greenhouse   census    all_postings        37         29                    1
44                                  Clear Street        fintech         greenhouse   census    all_postings        36         19                    2
45                     Dimensional Fund Advisors  asset_manager            workday   census  technical_only        30         30                    6
46                      Verition Fund Management     multistrat         greenhouse   census    all_postings        26         17                    2
47                             Wolverine Trading   market_maker           pinpoint   census    all_postings        24         19                    1
48                             Belvedere Trading   market_maker              lever   census    all_postings        21         13                    1
49                           Arrowstreet Capital     systematic            workday   census  technical_only        19         19                    2
50                                    Five Rings   prop_trading         greenhouse   census    all_postings        16         13                    0
51                        Bridgewater Associates     systematic         greenhouse   census    all_postings        15          6                    4
52                                   GSA Capital     systematic         greenhouse   census    all_postings        12         10                    1
53                                 Brevan Howard     multistrat            workday   census  technical_only        12         12                    3
54                     Graham Capital Management     systematic         greenhouse   census    all_postings         9          5                    1
55                                  PDT Partners     systematic         greenhouse   census  technical_only         9          9                    3
56                                        Winton  asset_manager         greenhouse   census    all_postings         9          7                    2
57                      XTX Markets Technologies     systematic         greenhouse   census    all_postings         9          8                    1
58                        Headlands Technologies   prop_trading         greenhouse   census    all_postings         8          6                    0
59                                 Radix Trading   prop_trading         greenhouse   census  technical_only         8          8                    0
60                                 Marshall Wace     systematic         greenhouse   census    all_postings         7          6                    0
61                            Quadrature Capital     systematic         greenhouse   census    all_postings         4          2                    0
62                           ExodusPoint Capital     multistrat         greenhouse   census    all_postings         2          0                    0
63                                         PEAK6   market_maker            workday   census  technical_only         1          1                    0

`Stored scope` matters when comparing the Postings column across firms. Some
adapters (Workday, Oracle) filter to technical titles before storing; the rest
store the whole board. So `n_postings` is not comparable across routes, while
`n_technical` is. The analysis uses technical denominators throughout.

In [3]:
print(f"{len(collected)} firms collected, {len(pending)} in the frame with no data\n")
for _, r in pending.iterrows():
    print(f"  {r['status']:12} {r['firm_name']}")

64 firms collected, 9 in the frame with no data

  unresolved   Acadian Asset Management
  broken       Balyasny Asset Management
  unresolved   BNP Paribas
  unsamplable  Capula Investment Management
  unsamplable  Hudson Bay Capital
  unresolved   Rokos Capital Management
  unsamplable  Susquehanna International Group
  unresolved   State Street Global Advisors
  unsamplable  UBS

Statuses are deliberately distinguished, because they would otherwise all read
as "no data":

- **unresolved** — not found yet. Says nothing about the firm. Discovery is
  non-deterministic: one firm resolved on one run and came back "no
  machine-readable board" on the next with its endpoint working the whole time.
- **unsamplable** — looked at, no route we can use. Mostly this means *we have
  not written the adapter*, not that the firm cannot be reached; that
  distinction is recorded per firm.
- **broken** — the route works in principle and the firm's own system is
  failing.

Per-firm caveats live in the manifest and travel into the frame, so a count and
its caveat cannot drift apart.

In [4]:
for _, r in frame[frame["limitations"] != ""].iterrows():
    print(f"{r['firm_name']} ({r['status']}, n={r['n_postings']})\n  {r['limitations']}\n")

AQR Capital Management (resolved, n=51)
  Postings name essentially no infrastructure products.

Arrowstreet Capital (resolved, n=19)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returned total=23 and requires offset paging (20 per page); a second site, Campus_Careers, on the same host/tenant holds 4 additional student/intern postings and must be queried separately to get full coverage.

Balyasny Asset Management (broken, n=0)
  Workday tenant returns HTTP 401 "Unable to verify credentials for system account 39$1476" on the CXS API and serves a "Workday is currently unavailable" page for individual roles. Failure is on the firm's side, not a block on us. Retry on each run.

Bank of America (resolved, n=220)
  POST to the CXS endpoint returns total=1950 with 20 postings per page (paginate via offset); this Workday site is experienced/lateral hiring only — campus/university roles live on a separate Avature board (bankcampuscareers.tal.net), and no other ghr site name resolved.

Barclays (resolved, n=421)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=784 and pages correctly at offset=760; Workday caps each response at 20 postings, so full harvest needs ~40 paged requests plus per-job /job/<externalPath> calls for descriptions.

Belvedere Trading (resolved, n=21)
  belvederetrading.com/careers links directly to jobs.lever.co/belvederetrading; the v0 postings endpoint returns all 21 live postings in one unpaginated response with full descriptions, so no sampling limitation beyond it showing only currently-published roles.

BlackRock (resolved, n=154)
  careers.blackrock.com is a Radancy/TalentBrew front end whose experienced-hire apply links all resolve to this Workday tenant (total 315, paginates cleanly to offset 300); early-career/campus postings are the sampling gap, since those apply through blackrock.tal.net and Beamery flows instead and are not in this Workday site (no other site name on the tenant responded).

Brevan Howard (resolved, n=12)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=28 and full pagination (offset=20 yields the remaining 8); brevanhoward.com/careers is a Phenom CareerConnect front-end (tenant BHABHAGB) but the underlying req/apply system is this Workday tenant, so a Phenom-only scrape could in principle surface postings not in this feed.

Bridgewater Associates (resolved, n=15)
  Public Greenhouse board carries ~15 roles total, far fewer than the firm hires. Token is only discoverable in the JSON embedded at bridgewater.com/jobboard. Any per-firm rate here rests on a handful of postings.

Capital Group (resolved, n=67)
  POST returned total=184 but only 20 per page, so full harvest requires paging offset in increments of 20 (limit caps at 20).

Capula Investment Management (unsamplable, n=0)
  Careers pages link exclusively to Workable. Workable has a public API but the account slug could not be determined; revisit if the slug is found.

Citadel (resolved, n=154)
  citadel.com blocks automated fetching (Cloudflare 403) for every client we tried. The live career sitemap supplies the URL list, but posting text comes from Wayback Machine snapshots, so vintages are mixed and some archived postings are no longer open. Treat Citadel counts as recent-history, not a current snapshot. Text extraction also picks up site navigation chrome, which is stripped in normalisation.

Citadel Securities (resolved, n=189)
  [medium confidence at discovery] Citadel Securities runs no third-party ATS — the apply form is their in-house Gild system posting to WordPress admin-ajax.php with an opaque job_id UUID — and all HTML careers pages are Cloudflare-challenged (403), so the only live machine-readable source is the Yoast career-sitemap.xml (82 posting URLs, lastmod 2026-09-28), with per-posting title/location scraped through the Wayback Machine, which means individual postings may be stale or missing relative to the sitemap.

Citi (resolved, n=1023)
  POST with {"appliedFacets":{},"limit":20,"offset":N,"searchText":""} works and reports total=2000, but offsets >=2000 silently wrap back to page 1 while the response facets sum to ~4383 postings, so full coverage requires paging per facet (e.g. Country_and_Jurisdiction); the citi.eightfold.ai/api/apply/v2/jobs?domain=citi.com alternative returns HTTP 403 "Not authorized for PCSX".

The D. E. Shaw Group (resolved, n=90)
  Server-rendered pages, text extracted from HTML. Some listings are umbrella "all positions in X" pages rather than single roles.

Deutsche Bank (resolved, n=361)
  POST {"appliedFacets":{},"limit":20,"offset":N,"searchText":""} returns total=1141 and paginates to offset 1120; limit is capped at 20 per request so full harvest needs ~58 paged calls, and per-job descriptions require the /wday/cxs/db/DBWebsite/job/<externalPath> detail endpoint.

Dimensional Fund Advisors (resolved, n=30)
  POST {"appliedFacets":{},"limit":20,"offset":N,"searchText":""} returns total=70 on the first page only (later pages report total=0), so paginate by offset until a page returns fewer than limit; the official careers.dimensional.com site links to this same dimensional.wd5.myworkdayjobs.com/DFA_Careers board, and list entries give titles/locations/externalPath but need a per-job fetch for full descriptions.

DRW (resolved, n=164)
  Listing comes from the __NEXT_DATA__ blob on the listings page; job text is scraped from each detail page's embedded props, so extraction is more fragile than a real API.

ExodusPoint Capital (resolved, n=2)
  Very small public board; counts are not meaningful alone.

Fidelity Investments (resolved, n=192)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=827 with 20 postings per page; tenant is fmr (FMR LLC, Fidelity's legal entity) and offset=800 still returns rows, but the API caps limit at 20 and reports total=0 on deep offsets, so pagination must loop on a non-empty jobPostings array rather than trusting total.

Flow Traders (resolved, n=47)
  Token read directly out of a fetch() call in the HTML of https://www.flowtraders.com/careers; API returned meta.total=47 with full content for every job, so no sampling limitation.

Goldman Sachs (resolved, n=559)
  Oracle Fusion tenant hdpc, site CX_2 (not the usual CX_1001, which returns an empty list). higher.gs.com is the marketing front end; this is the ATS behind it. Initially recorded unsamplable because our adapter had no site fallback, so the wrong site number looked like a firm with no board.

Graham Capital Management (resolved, n=9)
  Token read directly from the API_URL constant in the JS on https://www.grahamcapital.com/careers/; endpoint returns meta.total=9 with full content, so all postings are covered in one unpaginated response.

G-Research (resolved, n=53)
  POST with {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=64 and 20 postings per page; paginate by offset (offset=60 returned the final 4, but reports total=0 on non-first pages, so trust the first page's total).

Headlands Technologies (resolved, n=8)
  headlandstech.com/careers/ links apply buttons directly to job-boards.greenhouse.io/headlandstechnologiesllc, and the API returns all 8 postings with full content and meta.total=8, though one is a generic "Opportunistic Applications" evergreen req rather than a specific opening.

Hudson River Trading (resolved, n=87)
  Board token is not discoverable from hudsonrivertrading.com, which only links a two-post "talent community" board (token hrttalentcommunity). The real board is wehrtyou.

HSBC (resolved, n=1472)
  Eightfold API returns count=1467 and pages deep (start=1400 still returns global roles), but the server caps page size at 10 regardless of num, so a full pull needs ~147 sequential requests.

Hudson Bay Capital (unsamplable, n=0)
  No applicant-tracking system at all. The careers page is a static Webflow marketing page whose only application path is a mailto: address, so there is nothing to collect.

Invesco (resolved, n=90)
  careers.invesco.com fingerprints as myworkdayjobs; the IVZ site reports total=246 and paginates cleanly to offset 240, but a second Workday site (IVZearlycareers, tenant invesco, 6 postings) holds interns/early-career roles and must be scraped separately to get full coverage.

Jane Street (resolved, n=230)
  Postings name languages and systems but almost no infrastructure products. The only "airflow" matches are data-centre cooling roles and are excluded by the tool rules.

Jefferies (resolved, n=92)
  careers.jefferies.com is a Cloudflare-fronted vanity shim (returns 522 to curl) whose inline JS names the real Oracle Recruiting Cloud host hdid.fa.us2.oraclecloud.com, which serves all 167 experienced-hire postings (TotalJobsCount == items returned) in one unauthenticated GET; note that Jefferies runs campus/graduate recruiting on a separate Oleeo board at jefferies.tal.net, so student and intern programs are NOT in this feed.

JPMorganChase (resolved, n=2425)
  jpmorganchase.com/careers links to Oracle Recruiting CE site CX_1001 on jpmc.fa.oraclecloud.com; the REST finder returns TotalJobsCount 7494 and I sampled pages at offsets 0/50/100/200/1000/5000/7450/7490 (last page returned 4 rows, confirming full pagination) rather than downloading all 7494 — note that `offset` is silently ignored unless the `facetsList` finder argument is included, which would otherwise make every page identical.

Marshall Wace (resolved, n=7)
  mwam.com's own careers pages link to job-boards.greenhouse.io/mw-tech-grad; sampling limitation: Marshall Wace splits postings across several Greenhouse boards — mw-tech-grad (7 grad/associate roles) and mwinternshipprogram (7 internships) return postings, while the main 'marshallwace' board and 'mwam-imperial-placements' currently return 0, and experienced-hire roles appear to be agency-sourced rather than posted.

Millennium Management (resolved, n=215)
  List endpoint omits descriptions; each posting needs a second detail call.

Morgan Stanley (resolved, n=400)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=1345 and pages cleanly to offset 1300 (deep pages report total=0 but still return 20 postings, so paginate until an empty jobPostings array rather than trusting total); I directly sampled only 40 postings across two pages, and Morgan Stanley's morganstanley.eightfold.ai mirror returns 403 "Not authorized" so Workday is the usable endpoint.

Northern Trust (resolved, n=181)
  careers.northerntrust.com 301-redirects to ntrs.wd1.myworkdayjobs.com/northerntrust; POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=639 with 20 postings per page, and offset=620 still returns 19 rows, so full coverage requires paginating offset in steps of 20 (the `total` field reads 0 on non-zero-offset responses, so use the first page's total as the stop condition).

Optiver (resolved, n=166)
  Board token is optiverus, not optiver; the obvious guess returns an empty board. Found by discovery on 2026-09-25 but missed on the 2026-09-27 sweep, so it is pinned here rather than left to chance.

PEAK6 (resolved, n=1)
  peak6.com/careers is an Ongig embed (text-analyzer.ongig.com, group_id 1767) whose 75 listings all apply into Workday tenant peak6group split across 7 CXS sites, so the PEAK6 site alone returns only 14 (incl. the trading associate/internship reqs); scrape the siblings too for full coverage: apexfintechsolutions (49), WeInsure (5), CapMan (3), Bruce (2), ppcareers (1), TFIG (1), plus empty evilgeniuses/zogo.

PIMCO (resolved, n=84)
  POST with {"appliedFacets":{},"limit":20,"offset":N,"searchText":""} returns total=195 on the first page and paginates cleanly to offset=180 (15 rows), but limit is capped at 20 per request and the `total` field reports 0 on non-zero offsets, so paginate until an empty page rather than trusting `total`.

Quadrature Capital (resolved, n=4)
  Very small public board (single digits); counts are not meaningful alone.

Qube Research & Technologies (resolved, n=199)
  qube-rt.com/careers is 403/robots-disallowed to crawlers, but real apply links resolve to job-boards.greenhouse.io/quberesearchandtechnologies and the Greenhouse API returns all 199 postings with full content in one unpaginated call (meta.total=199).

Radix Trading (resolved, n=8)
  Radix Trading (radixtrading.co) splits postings across TWO Greenhouse boards linked from its homepage — radixuniversity (8 jobs, students/postdocs) and radixexperienced (7 jobs, https://boards-api.greenhouse.io/v1/boards/radixexperienced/jobs?content=true) — so scraping only one token samples roughly half of the 15 open roles.

Schonfeld Strategic Advisors (resolved, n=80)
  Standardised on Prefect; their stack blurb "AWS, Prefect, Coder, Kubernetes" recurs across unrelated roles, so Prefect counts here are driven by boilerplate repetition as much as by distinct requirements.

Susquehanna International Group (unsamplable, n=0)
  Careers site runs on iCIMS behind a Jibe front end (careers.sig.com, client code 'sig'). Endpoint exists; we have no adapter for iCIMS/Jibe.

T. Rowe Price (resolved, n=63)
  POST returned total=138 with 20 postings per page (paginate via offset); a second site 'TRowePriceInternational' on the same host/tenant holds 29 additional non-US postings, so scraping only the TRowePrice site misses international roles.

Two Sigma (resolved, n=53)
  Avature portal. Detail URLs ignore the slug, only the numeric id matters. Text is extracted from server-rendered HTML, not an API.

UBS (unsamplable, n=0)
  Board runs on IBM Kenexa BrassRing Talent Gateway (jobs.ubs.com/TGnewUI, partnerid 25008, several siteids). Endpoint exists; we have no adapter for BrassRing.

Vanguard (resolved, n=211)
  POST {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returns total=401 and 20 postings per page; www.vanguardjobs.com is a Symphony Talent/m-cloud WordPress front end whose embedded config names Workday as the ATS, and paging to offset=380 still returns rows (the `total` field resets to 0 on non-zero offsets, so page until jobPostings is empty rather than trusting it).

Verition Fund Management (resolved, n=26)
  Token read from the Greenhouse embed script (for=veritiongroupllc) on https://www.verition.com/open-positions, whose gh_jid links match ids in the API; the single content=true call returned all 26 jobs (meta.total=26), so no pagination limitation.

The Voleon Group (resolved, n=53)
  voleon.com/jobs embeds jobs.ashbyhq.com/voleon/embed?version=2 and the Ashby posting API returns all 53 live postings in one unpaginated response; a stale Lever board (jobs.lever.co/voleon) still exists but its API returns an empty array.

Wellington Management (resolved, n=76)
  POST with {"appliedFacets":{},"limit":20,"offset":0,"searchText":""} returned HTTP 200 with total=129 but only 20 postings per page, so pagination via offset is required to retrieve all listings.

Wells Fargo (resolved, n=171)
  POST with {"appliedFacets":{},"limit":20,"offset":N,"searchText":""} returns total=1705 and 20 postings per page (max limit 20); offset=1700 returns the final 5, confirming full pagination, though `total` is only populated on the offset=0 request and reads 0 on subsequent pages — the mirror host wd1.myworkdaysite.com with path /wday/cxs/wf/WellsFargoJobs/jobs returns byte-identical results.

Wolverine Trading (resolved, n=24)
  Pinpoint board at careers.wolve.com (wolve.com is the corporate domain). Adapter added 2026-09-27 after discovery identified the platform but had no route for it.

XTX Markets Technologies (resolved, n=9)
  Only the technology subsidiary posts to this board; XTX's main hiring is elsewhere, so the sample is a small slice of the firm.

## Three denominators

A share is meaningless without its denominator, and the choice moves the answer
by a factor of five.

- **all_technical** — every posting with a technical title. Wide; it includes
  low-latency C++ and trading roles that would never name an orchestrator, so it
  *understates* prevalence among the people who build pipelines.
- **pipeline_mentioning** — technical postings whose text mentions a pipeline,
  ETL/ELT or orchestration. Much closer to the population the course is about,
  but selected on the outcome's own vocabulary, so it *overstates* prevalence
  relative to engineering hiring generally.
- **pipeline_distinct_roles** — the same pool with one row per (firm, title), so
  a role advertised in six offices counts once. The robustness check.

In [5]:
summary = d["summary"]
denoms = (
    summary[summary["firm_type"] == "ALL"][["denominator", "denominator_n", "n_firms_in_pool"]]
    .drop_duplicates()
    .set_index("denominator")
)
denoms

                         denominator_n  n_firms_in_pool
denominator
all_technical                     9237               63
pipeline_distinct_roles           1349               57
pipeline_mentioning               1600               57

## Excluding trading roles: what it costs

The technical-title filter excludes trading roles. That is a choice, so here is
what it discards: postings with a trading title that fail the filter, and how
many tool mentions are inside them.

In [6]:
import re

idx, long = d["idx"], d["long"]
TRADE = re.compile(r"\btrad(?:er|ing)\b|\bmarket mak", re.IGNORECASE)
excluded = idx[(~idx["is_technical"]) & (idx["title"].str.contains(TRADE))]
ids = set(excluded["posting_id"])
inside = long[long["posting_id"].isin(ids)]
print(f"postings with a trading title excluded by the filter: {len(excluded)}")
print(f"  as a share of all {len(idx):,} postings: {len(excluded) / len(idx):.1%}")
print(f"  tool mentions inside them: {len(inside)}")
if len(inside):
    print(inside.groupby("display").size().sort_values(ascending=False).head(8).to_string())

postings with a trading title excluded by the filter: 157
  as a share of all 11,346 postings: 1.4%
  tool mentions inside them: 184
display
Python                                      77
SQL (any dialect)                           34
R                                           16
C++                                         12
Data-quality / validation work (generic)    10
Bloomberg                                    7
MATLAB                                       5
kdb+ / q                                     5

## Four ways of counting, and why the choice matters more than the sample size

Firms differ in board size by three orders of magnitude, from a handful of
postings to several thousand. So "what share of postings name this tool" is
largely a statement about whoever posts the most.

- **n_postings / n_firms** — raw counts, no weighting. Look at these first.
- **% firms naming it** — the extensive margin: the fraction of firms with at
  least one such posting. The most assumption-light. A firm cannot inflate it by
  posting more, by reposting one role across offices, or by repeating a stack
  blurb. It cannot distinguish one mention from many.
- **% postings (pooled)** — total mentions over total postings. Dominated by the
  largest boards.
- **% postings (firm mean)** — equal weight per firm. Immune to board size, but
  a two-posting firm reports 0% or 50% as though either were a measurement.
- **% postings (shrunk)** — the firm mean with each rate pulled toward the
  pooled rate in proportion to how little data the firm has (beta-binomial
  empirical Bayes).

`index/firm_rates.csv` holds the numerator and denominator behind every firm, so
the shrinkage is inspectable rather than a black box.

In [7]:
report.tools_table(d["summary"], layers=report.SCHEDULING_LAYERS)

                         Tool                 Layer  Postings  Firms  Firms in pool  % firms naming it  % postings (shrunk)  % postings (firm mean)  % postings (pooled)
0              Apache Airflow          orchestrator       164     33             57               57.9                 13.1                    13.8                 10.2
1                     Dagster          orchestrator        23     14             57               24.6                  1.8                     3.7                  1.4
2                       Slurm         hpc_scheduler        26     12             57               21.1                  2.2                     4.1                  1.6
3    Argo Workflows / Argo CD      durable_workflow        23     10             57               17.5                  1.5                     1.6                  1.4
4                  CA AutoSys  enterprise_scheduler        28      9             57               15.8                  1.7                     0.9                  1.8
5                     Prefect          orchestrator        13      9             57               15.8                  1.1                     3.5                  0.8
6          AWS Step Functions      durable_workflow        42      8             57               14.0                  2.3                     1.3                  2.6
7               BMC Control-M  enterprise_scheduler        25      8             57               14.0                  1.8                     1.6                  1.6
8          Azure Data Factory      durable_workflow        10      6             57               10.5                  0.6                     0.4                  0.6
9                 Temporal.io      durable_workflow        20      5             57                8.8                  1.1                     0.4                  1.2
10                Hadoop YARN         hpc_scheduler         9      5             57                8.8                  0.6                     0.3                  0.6
11                      Kueue         hpc_scheduler         2      2             57                3.5                  0.2                     0.2                  0.1
12           Make / Makefiles          build_runner         2      2             57                3.5                  0.1                     0.1                  0.1
13      cron / systemd timers  enterprise_scheduler         1      1             57                1.8                  0.1                     0.0                  0.1
14                   HTCondor         hpc_scheduler         1      1             57                1.8                  0.1                     0.1                  0.1
15                      Luigi          orchestrator         1      1             57                1.8                  0.1                     0.0                  0.1
16                Apache NiFi      durable_workflow         1      1             57                1.8                  0.1                     0.0                  0.1
17  Tidal Workload Automation  enterprise_scheduler         1      1             57                1.8                  0.1                     0.0                  0.1

### The estimators, demonstrated

One firm with a single posting that names the tool, against one firm with a
thousand postings that never does. Watch what each estimator does as the small
firm gains data.

In [8]:
import pandas as pd

from jobpostings.index import _estimators

rows = []
for size in (1, 10, 100, 1000):
    e = _estimators(pd.Series([size, 0]), pd.Series([size, 1000]))
    rows.append(
        {
            "mentioning firm's postings": size,
            "% firms naming it": round(e["firms_any"] * 100, 1),
            "pooled": round(e["pooled"] * 100, 2),
            "firm mean": round(e["firm_mean"] * 100, 2),
            "shrunk": round(e["shrunk"] * 100, 2),
        }
    )
pd.DataFrame(rows)

   mentioning firm's postings  % firms naming it  pooled  firm mean  shrunk
0                           1               50.0    0.10       50.0    2.43
1                          10               50.0    0.99       50.0   17.01
2                         100               50.0    9.09       50.0   42.51
3                        1000               50.0   50.00       50.0   50.00

The firm mean always gives the one-posting firm half the vote. Pooled almost
never does. The shrunk estimate earns its way from one to the other as evidence
accumulates. The extensive margin sits at 50% throughout, because it only asks
*whether* a firm names the tool, never how loudly.

One property worth stating because it is easy to assume otherwise: the shrunk
estimate does **not** have to lie between the firm mean and the pooled rate. It
is a per-firm convex combination that is then averaged, so when firm size
correlates with a firm's own rate it can sit outside that interval. It does so
for a small number of rows in this corpus, by small margins.

### A live test: does the weighting hold when one firm gets huge?

Collection was briefly capped at 250 postings per firm as a storage budget. When
the cap was removed, one firm's contribution grew roughly tenfold and the corpus
grew by half. That is a natural experiment on the estimators, and the results
are recorded here because they are the justification for the weighting scheme:

| estimator | mean absolute move | max | rows moving >1pp |
|---|---|---|---|
| % postings (firm mean) | 0.078pp | 0.474pp | 0 |
| % postings (shrunk) | 0.410pp | 3.067pp | 9 |
| % postings (pooled) | 0.881pp | 7.319pp | 15 |
| % firms naming it | 1.025pp | 5.263pp | 32 |

Equal weight per firm was essentially immune: not one row moved by a percentage
point. Pooled moved as a volume-weighted statistic must, shifting toward the new
firm's profile — Java +7.3pp, CI/CD +6.9, Kubernetes +5.1, Terraform +4.8 — none
of which reflects a change in the market.

The extensive margin moved most, which refutes a claim made earlier in this
work. It is immune to *volume inflation of a mention already counted*, but not
to *discovering a mention that truncation had hidden*. 32 tools gained firms and
none lost any: a strictly one-directional correction, so the cap had been
biasing the firm count downward. Capping is now opt-in and unused.

## Who names no orchestrator at all

Not random, and not a gap in the data. Latency-first proprietary shops describe
building their own scheduling layer instead of adopting a product.

In [9]:
ORCH = ["airflow", "prefect", "dagster", "luigi", "control_m", "autosys"]
per_firm = (
    long[long["tool"].isin(ORCH)]
    .pivot_table(index="firm", columns="tool", values="posting_id", aggfunc="nunique")
    .reindex(columns=ORCH)
    .fillna(0)
    .astype(int)
)
tech = idx[idx["denom_all_technical"]].groupby("firm").size().rename("technical")
names = frame.set_index("firm")[["firm_name", "firm_type"]]
table = names.join(tech, how="right").join(per_firm).fillna(0)
for c in table.columns:
    if c not in ("firm_name", "firm_type"):
        table[c] = table[c].astype(int)
none_named = table[table[ORCH].sum(axis=1) == 0]
substantial = none_named[none_named["technical"] >= 20].sort_values(
    "technical", ascending=False
)
print("Firms with 20+ technical postings naming no orchestration product:\n")
for _, r in substantial.iterrows():
    print(f"  {r['firm_name']:30} {r['technical']:5d} technical  ({r['firm_type']})")
print(f"\n{int(substantial['technical'].sum()):,} technical postings at those firms.")

Firms with 20+ technical postings naming no orchestration product:

  Jane Street                      150 technical  (prop_trading)
  Citadel                          108 technical  (multistrat)
  Jump Trading                      94 technical  (prop_trading)
  PIMCO                             84 technical  (asset_manager)
  Hudson River Trading              62 technical  (prop_trading)
  Two Sigma                         43 technical  (systematic)
  The D. E. Shaw Group              42 technical  (systematic)
  AQR Capital Management            36 technical  (systematic)
  Akuna Capital                     33 technical  (market_maker)
  Old Mission Capital               29 technical  (market_maker)

681 technical postings at those firms.

## Every other layer

The full ranking for each layer, so the syllabus can be argued from the data
rather than from the orchestration slice alone.

In [10]:
LAYERS = [
    "transform", "datastore", "streaming", "storage_format", "container",
    "ci", "data_quality", "mlops", "ingestion", "vendor_data", "language",
]
for layer in LAYERS:
    t = report.tools_table(d["summary"], layers=[layer])
    if t.empty:
        continue
    print(f"\n=== {layer} ===")
    print(
        t[["Tool", "Postings", "Firms", "% firms naming it", "% postings (shrunk)"]]
        .to_string(index=False)
    )

=== transform ===
        Tool  Postings  Firms  % firms naming it  % postings (shrunk)
Apache Spark       297     28               49.1                 14.6
      pandas        98     26               45.6                  7.2
       NumPy        69     20               35.1                  4.8
         dbt        50     14               24.6                  3.3
         Ray        31     11               19.3                  2.6
        Dask        21     11               19.3                  1.6
      Polars        20     11               19.3                  1.6
      DuckDB         5      3                5.3                  0.4

=== datastore ===
             Tool  Postings  Firms  % firms naming it  % postings (shrunk)
SQL (any dialect)       599     46               80.7                 37.5
       PostgreSQL       162     32               56.1                 12.5
        Snowflake       195     25               43.9                 11.7
          MongoDB       104     19               33.3                  5.6
            Redis        77     19               33.3                  4.5
       Databricks       212     18               31.6                 10.5
         BigQuery        32     11               19.3                  2.3
       ClickHouse        13      8               14.0                  1.1
         kdb+ / q        19      7               12.3                  1.5
         ArcticDB         6      1                1.8                  0.6

=== streaming ===
        Tool  Postings  Firms  % firms naming it  % postings (shrunk)
Apache Kafka       322     36               63.2                 18.7
Apache Flink        53     14               24.6                  2.9
    RabbitMQ        32     10               17.5                  1.8
 AWS Kinesis        18      6               10.5                  1.1

=== storage_format ===
          Tool  Postings  Firms  % firms naming it  % postings (shrunk)
Apache Iceberg        66     14               24.6                  3.7
    Delta Lake        55     13               22.8                  3.1
Apache Parquet        44     12               21.1                  2.6
  Apache Arrow        12      6               10.5                  0.9

=== container ===
      Tool  Postings  Firms  % firms naming it  % postings (shrunk)
Kubernetes       601     40               70.2                 33.0
    Docker       477     38               66.7                 26.6
      Helm        37     18               31.6                  2.4

=== ci ===
           Tool  Postings  Firms  % firms naming it  % postings (shrunk)
CI/CD (generic)       843     44               77.2                 44.3
      Terraform       362     37               64.9                 18.7
        Jenkins       219     25               43.9                 11.1
 GitHub Actions        67     17               29.8                  3.7
      GitLab CI        54     14               24.6                  2.8
       TeamCity        13      5                8.8                  0.8

=== data_quality ===
                                           Tool  Postings  Firms  % firms naming it  % postings (shrunk)
       Data-quality / validation work (generic)       478     46               80.7                 29.1
Reproducibility / versioning language (generic)       103     26               45.6                  6.5
                             Great Expectations         8      5                8.8                  0.5

=== mlops ===
         Tool  Postings  Firms  % firms naming it  % postings (shrunk)
       MLflow        31     13               22.8                  1.9
AWS SageMaker        32     10               17.5                  1.9
Feature store        19      9               15.8                  1.2
     Kubeflow        14      7               12.3                  0.8

=== ingestion ===
                  Tool  Postings  Firms  % firms naming it  % postings (shrunk)
dlt / Meltano / Singer         7      2                3.5                  0.4
               Airbyte         1      1                1.8                  0.1

=== vendor_data ===
                      Tool  Postings  Firms  % firms naming it  % postings (shrunk)
Alternative data (generic)        28     13               22.8                  2.5
                 Bloomberg        17     13               22.8                  2.9
          LSEG / Refinitiv        10      8               14.0                  1.6
         ICE Data Services         8      6               10.5                  1.0
                   FactSet         4      2                3.5                  0.6
               FINRA TRACE         1      1                1.8                  0.1

=== language ===
        Tool  Postings  Firms  % firms naming it  % postings (shrunk)
      Python      1131     53               93.0                 72.8
        Java       574     36               63.2                 27.2
Bash / shell       133     32               56.1                  8.5
         C++       143     29               50.9                 13.5
          Go       139     27               47.4                  8.4
        Rust        63     20               35.1                  5.3
       Scala        61     20               35.1                  3.6
           R        37     16               28.1                  2.6
      MATLAB         1      1                1.8                  0.1

## How a mention is decided

Every feature comes from a declarative rule in `src/tool_rules.yml`. The rules
carry context tests because a naive keyword search is wrong in ways that change
conclusions, and they are unit-tested against the exact strings that fooled
earlier versions.

The clearest case: "airflow" is also a facilities term. At two firms in this
corpus the only matches were data-centre cooling roles, and counting those would
have put a firm that never names an orchestrator at the top of the Airflow list.

In [11]:
rules = (d["root"] / "src" / "tool_rules.yml").read_text()
start, end = rules.index("  airflow:"), rules.index("  dagster:")
print(rules[start:end].rstrip())

  airflow:
    display: Apache Airflow
    layer: orchestrator
    patterns: ['\bairflow\b']
    exclude_if_context:
      - 'cooling'
      - '\brack(-|\s)?level\b'
      - '\bracks?\b'
      - 'CRAH|CRAC|HVAC'
      - 'airflow management'
      - 'liquid cooling'
      - 'containment'
      - 'data cent(er|re)'
      - '\bCDUs?\b|\bRDHx\b'
    note: >-
      "Airflow" is also a facilities term. Jane Street's and HRT's only matches
      were data-centre cooling roles ("redundancy topologies, containment,
      airflow management", "rack-level cooling and airflow"). Excluding those is
      the difference between Jane Street appearing to be an Airflow shop and the
      truth, which is that it never names an orchestrator.

Other traps the rules guard against, each found by getting it wrong first:
`scalable` matching Scala, `array` matching Ray, "temporal data" matching
Temporal.io, a stack trace matching FINRA TRACE, Monte Carlo simulation matching
a data-observability vendor, and Yarn the JavaScript package manager matching
Hadoop YARN.

## Worked evidence

Counts are only as good as the sentences behind them. These are pulled
programmatically from the corpus, so they cannot drift from the numbers above.

In [12]:
import json


def quotes(tool: str, limit: int = 6, window: int = 150) -> None:
    """Print real sentences behind a tool's count, at most one per firm."""
    hits = set(long[long["tool"] == tool]["posting_id"])
    meta = idx.set_index("posting_id")
    seen, shown = set(), 0
    for path in sorted((d["data_dir"] / "postings").glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if shown >= limit:
                return
            rec = json.loads(line)
            if rec["posting_id"] not in hits or rec["firm"] in seen:
                continue
            m = re.search(rf"\b{tool}\b", rec["text"], re.IGNORECASE)
            if not m:
                continue
            seen.add(rec["firm"])
            lo, hi = max(0, m.start() - window), min(len(rec["text"]), m.end() + window)
            firm = meta.loc[rec["posting_id"], "firm_name"]
            print(f"[{firm} — {rec['title']}]\n  ...{rec['text'][lo:hi]}...\n")
            shown += 1


quotes("airflow", limit=6)

[Bank of America — Quantitative Finance Analyst]
  ...ata stores and big data environments. Hands-on expertise with data technologies and computing frameworks including but not limited to, Python, Spark, Airflow, Javascript and SQL. Ability to research new data technologies, architect novel data solutions for business problems and prove design approach throug...

[Barclays — AVP - Data Scientist & AI Engineer]
  ...be expected to work hands-on across on prem & cloud Compliance AI Platform. This requires strong proficiency in data ingestion and processing (Kafka, Airflow, Spark), cloud-based data platforms (Databricks, Snowflake, AWS S3/Azure), and SQL-based data transformation (dbt, PySpark). The candidate must demon...

[BlackRock — Data Engineer – AWS Native Data Platforms, Vice President]
  ...pelines for batch and event‑driven workloads, with a focus on reliability, scalability, and security. Develop and operate data workflows using Apache Airflow for orchestration and Python and SQL for transformation and data quality logic. Implement data transformations and models using modern analytics engi...

[Brevan Howard — Front Office Data Engineer]
  ...ations. Desirable Experience working with market data providers such as Bloomberg, Refinitiv or ICE. Experience with orchestration frameworks such as Airflow, Prefect or Dagster. Experience building internal tools or dashboards using Dash, Streamlit or similar frameworks. Experience with GoldenSource or ot...

[Bridgewater Associates — Research Associate, Equities Data Engineer]
  ...ata-aria-posinset="5" data-aria-level="1"><span data-contrast="auto">Familiarity with distributed processing and workflow orchestration (e.g., Spark, Airflow, or equivalents).</span><span data-ccp-props="{&quot;335551550&quot;:1,&quot;335551620&quot;:1}">&nbsp;</span></li> </ul> <ul> <li data-leveltext=""...

[Capital Group — Data and AI Engineering Manager]
  ...ed Qualifications : 10+ years building full-stack data products end-to-end, hands-on across a modern lakehouse stack (Databricks, Unity Catalog, dbt, Airflow/Astronomer); Databricks Apps experience a plus Software engineering depth across multi-tier systems, with hands-on experience delivering information ...

In [13]:
quotes("control_m", limit=3)

In [14]:
quotes("dagster", limit=3)

[Barclays — Data Engineer - Analyst]
  ...ood communication skills (both verbal and written) Desirable skills/Preferred Qualifications: • Experience with orchestration tools (Snowflake Tasks, Dagster, Prefect) • Experience in data visualization and data analytics infra using Tableau (or similar BI tool) will be a value add • Past experience with l...

[BlackRock — Senior Data Architect/Data Engineer, Aladdin Engineering - Vice President]
  ...s layer approach. Exposure to orchestration tools (e.g., Directed acyclic graph-based workflow orchestration framework for data and batch processing, Dagster, Prefect) and patterns for dependency management and backfills. Streaming and event-driven data experience (e.g., distributed event streaming and mes...

[Brevan Howard — Front Office Data Engineer]
  ...perience working with market data providers such as Bloomberg, Refinitiv or ICE. Experience with orchestration frameworks such as Airflow, Prefect or Dagster. Experience building internal tools or dashboards using Dash, Streamlit or similar frameworks. Experience with GoldenSource or other enterprise data ...

## Collection history

One row per run. Several runs are needed before any trend claim is available;
`observations.csv` is built so the same tables can be recomputed per run.

In [15]:
runs_table = (
    pd.read_csv(d["data_dir"] / "run_log.csv")
    .groupby("run_date")
    .agg(firms=("firm", "nunique"), postings=("n_in_run", "sum"), new=("new", "sum"))
)
runs_table

            firms  postings   new
run_date
2026-09-25     28      1993  1993
2026-09-27     64      7655  5664

## Where the language model is, and is not

`src/discover_sources.py` asks Claude exactly one question per firm: which
applicant-tracking system, and what is the endpoint? That is genuinely fuzzy
work — one firm's board token is `wehrtyou`, another's appears only inside JSON
embedded in an unrelated page, a third's differs from the obvious guess by two
characters and the obvious guess returns an empty board.

The answer is then validated by calling the endpoint and requiring real postings
back before anything is written to the manifest.

**Claude never reads a posting, never extracts a feature and never produces a
number.** Every count here comes from the declarative regexes above. The
proposer does not have to be trusted, because the gate confers the trust: a
hand-written proposal clears exactly the same check.

That boundary generalises well beyond job postings. Use the model where judgment
is cheap to check and expensive to automate, and keep it away from anything you
intend to report as a measurement.